// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FriendMessageCfm;
@class FriendMessageReq;
@class FriendMessageRes;
@class OfflineMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : GPBRootObject
@end

#pragma mark - QueryFriendReq

typedef GPB_ENUM(QueryFriendReq_FieldNumber) {
  QueryFriendReq_FieldNumber_Pk = 1,
};

@interface QueryFriendReq : GPBMessage

/** hex show */
@property(nonatomic, readwrite, copy, null_resettable) NSData *pk;

@end

#pragma mark - QueryFriendRes

typedef GPB_ENUM(QueryFriendRes_FieldNumber) {
  QueryFriendRes_FieldNumber_Exist = 1,
  QueryFriendRes_FieldNumber_Pk = 2,
};

@interface QueryFriendRes : GPBMessage

@property(nonatomic, readwrite) uint32_t exist;

@property(nonatomic, readwrite, copy, null_resettable) NSData *pk;

@end

#pragma mark - OfflineMessageReq

typedef GPB_ENUM(OfflineMessageReq_FieldNumber) {
  OfflineMessageReq_FieldNumber_LocalMsgId = 1,
  OfflineMessageReq_FieldNumber_ToPk = 2,
  OfflineMessageReq_FieldNumber_CryptoMessage = 3,
};

@interface OfflineMessageReq : GPBMessage

@property(nonatomic, readwrite) int64_t localMsgId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toPk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *cryptoMessage;

@end

#pragma mark - OfflineMessageReadNotice

typedef GPB_ENUM(OfflineMessageReadNotice_FieldNumber) {
  OfflineMessageReadNotice_FieldNumber_LatestMsgId = 1,
};

@interface OfflineMessageReadNotice : GPBMessage

@property(nonatomic, readwrite) uint64_t latestMsgId;

@end

#pragma mark - OfflineMessage

typedef GPB_ENUM(OfflineMessage_FieldNumber) {
  OfflineMessage_FieldNumber_LocalMsgId = 1,
  OfflineMessage_FieldNumber_MsgId = 2,
  OfflineMessage_FieldNumber_FrPk = 3,
  OfflineMessage_FieldNumber_ToPk = 4,
  OfflineMessage_FieldNumber_Content = 5,
  OfflineMessage_FieldNumber_CreateTime = 6,
};

@interface OfflineMessage : GPBMessage

@property(nonatomic, readwrite) int64_t localMsgId;

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *frPk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toPk;

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@property(nonatomic, readwrite) uint64_t createTime;

@end

#pragma mark - OfflineMessagePullReq

@interface OfflineMessagePullReq : GPBMessage

@end

#pragma mark - OfflineMessagePullRes

typedef GPB_ENUM(OfflineMessagePullRes_FieldNumber) {
  OfflineMessagePullRes_FieldNumber_MsgArray = 1,
  OfflineMessagePullRes_FieldNumber_LeftCount = 2,
};

@interface OfflineMessagePullRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OfflineMessage*> *msgArray;
/** The number of items in @c msgArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgArray_Count;

@property(nonatomic, readwrite) uint32_t leftCount;

@end

#pragma mark - OfflineMessageDelReq

typedef GPB_ENUM(OfflineMessageDelReq_FieldNumber) {
  OfflineMessageDelReq_FieldNumber_LastMsgId = 2,
};

@interface OfflineMessageDelReq : GPBMessage

/** last of message id to be deleted */
@property(nonatomic, readwrite) uint64_t lastMsgId;

@end

#pragma mark - FriendMessageReq

typedef GPB_ENUM(FriendMessageReq_FieldNumber) {
  FriendMessageReq_FieldNumber_Msg = 1,
  FriendMessageReq_FieldNumber_LocalMsgId = 2,
};

@interface FriendMessageReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *msg;

/** generate msg id locally, unique globally，maybe unixtime */
@property(nonatomic, readwrite) uint64_t localMsgId;

@end

#pragma mark - FriendMessageRes

typedef GPB_ENUM(FriendMessageRes_FieldNumber) {
  FriendMessageRes_FieldNumber_LocalMsgId = 1,
};

@interface FriendMessageRes : GPBMessage

@property(nonatomic, readwrite) uint64_t localMsgId;

@end

#pragma mark - FriendMessageCfm

typedef GPB_ENUM(FriendMessageCfm_FieldNumber) {
  FriendMessageCfm_FieldNumber_SendStatus = 1,
  FriendMessageCfm_FieldNumber_LocalMsgId = 2,
};

@interface FriendMessageCfm : GPBMessage

/** send status, 0 means ok, else means failed */
@property(nonatomic, readwrite) uint32_t sendStatus;

@property(nonatomic, readwrite) uint64_t localMsgId;

@end

#pragma mark - FriendMessage

typedef GPB_ENUM(FriendMessage_FieldNumber) {
  FriendMessage_FieldNumber_FriendMsgReq = 1,
};

@interface FriendMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) FriendMessageReq *friendMsgReq;
/** Test to see if @c friendMsgReq has been set. */
@property(nonatomic, readwrite) BOOL hasFriendMsgReq;

@end

#pragma mark - EchoMessage

typedef GPB_ENUM(EchoMessage_FieldNumber) {
  EchoMessage_FieldNumber_FriendMsgRes = 1,
};

@interface EchoMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) FriendMessageRes *friendMsgRes;
/** Test to see if @c friendMsgRes has been set. */
@property(nonatomic, readwrite) BOOL hasFriendMsgRes;

@end

#pragma mark - ConfirmMessage

typedef GPB_ENUM(ConfirmMessage_FieldNumber) {
  ConfirmMessage_FieldNumber_FriendMsgCfm = 1,
};

@interface ConfirmMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) FriendMessageCfm *friendMsgCfm;
/** Test to see if @c friendMsgCfm has been set. */
@property(nonatomic, readwrite) BOOL hasFriendMsgCfm;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
